- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: "Install Common Packages"
  yum:
    name:
      - epel-release
      - wget
      - firewalld
      - git
      - htop
      - policycoreutils-python-utils-2.9-9.el8
    state: latest