---

- name: Centos Install Tasks
  include_tasks: common_linux.yml
  when: ansible_os_family == "RedHat"

- name: Ubuntu Install Tasks
  include_tasks: common_ubuntu.yml
  when: ansible_os_family == "Debian"
