- name: "Generate config"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: "app.py.j2", mode: "0755", dest: "/usr/bin/app.py" }

- name: "Install Flask"
  pip:
    name:
      - flask
      - flask-mysql

- name: "Create Temp DB Creds"
  shell: |
   > /tmp/creds
   printf '{{db_name}},\n{{db_user}},\n{{db_user_password}}\n{{db_host}}' >> /tmp/creds

- name: Start web-application
  command: /usr/bin/app.py nohup flask run --host=0.0.0.0 &