- name: "Generate config"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: "app.py.j2", mode: "0755", dest: "/usr/bin/app.py" }

- name: "Install Flask"
  pip:
    name:
      - flask
      - flask-mysql

- name: "Create Temp DB Creds"
  shell: |
   > /tmp/creds
   printf '{{db_name}},{{db_user}},{{db_user_password}},{{db_host}}' >> /tmp/creds

- name: Start web-application
  shell: | 
    export FLASK_APP=/usr/bin/app.py
    /usr/local/bin/flask run --host=127.0.0.1 --port=80 &