- name: "Generate config"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: "app.py.j2", mode: "0755", dest: "/usr/bin/app.py" }
    - { src: "start_service.sh.j2", mode: "0755", dest: "/usr/bin/start_service.sh" }
    - { src: "web_app.service.j2", mode: "0644", dest: "/etc/systemd/system/web_app.service" } 

- name: "Install Flask"
  pip:
    name:
      - flask
      - flask-mysql

- name: "Create Temp DB Creds"
  shell: |
   > /tmp/creds
   printf '{{db_name}},{{db_user}},{{db_user_password}}' >> /tmp/creds

- name: Start web-application
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: web_app.service