---
- name: Database Servers
  hosts: db_servers
  remote_user: root
  become: yes

  roles:
   - common
   - db

- name: Web Servers
  hosts: web_servers
  remote_user: root
  become: yes

  roles:
   - common
   - web

- name: LB Servers
  hosts: lb_servers
  remote_user: root
  become: yes

  roles: 
    - common
    - lb