---
- name: Database Servers
  hosts: db-server-*
  remote_user: centos
  become: yes

  roles:
   - common
   - db

- name: Web Servers
  hosts: web-server-*
  remote_user: centos
  become: yes

  roles:
   - common
   - web

- name: LB Servers
  hosts: lb-server-*
  remote_user: centos
  become: yes

  roles: 
    - common
    - lb